version: "3.7"
services:
  app:
    build:
      args:
        user: kynderman
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: mvcphp
    container_name: mvcphp-app
    ports:
      - 8000:80
    restart: unless-stopped
    working_dir: /var/www/html/mvcphp
    volumes:
      - ./:/var/www/html/mvcphp
    networks:
      - mvcphp

  db:
    image: mysql:5.7
    container_name: mvcphp-db
    restart: unless-stopped
    ports:
        - ${DB_PORT}:${DB_PORT}
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - mvcphp

networks:
  mvcphp:
    driver: bridge
